//def CODE_CHANGES = getGitChanges() - need plugin in jenkins
def CODE_CHANGES = true

pipeline {
	agent any
	environment {
		NEW_VERSION = '1.3.0'
		SERVER_CREDENTIALS = credentials('GitLab-nana-java-maven-app')
	}

	parameters {
		choice(name: 'VERSION', choices: ['1.0.0', '1.1.0', '1.2.0'], description: '')
		booleanParam(name: 'executeTests', defaultValue: true, description: '')
	}

	stages {
		stage('build') {
            when {
                expression {
                    env.GIT_BRANCH == 'origin/dev' || env.GIT_BRANCH == 'dev' || CODE_CHANGES
                }
            }
            steps {
                echo 'building the app...'
                echo "building version ${NEW_VERSION}"
                echo "GIT_BRANCH=${env.GIT_BRANCH}"
            }
        }

        stage('test') {
            when {
                allOf {
                    expression {
                        env.GIT_BRANCH == 'origin/dev' ||
                        env.GIT_BRANCH == 'dev' ||
                        env.GIT_BRANCH == 'origin/master' ||
                        env.GIT_BRANCH == 'master'
                    }
                    expression {
                        params.executeTests
                    }
                }
            }
            steps {
                echo 'testing the app...'
                echo "GIT_BRANCH=${env.GIT_BRANCH}"
            }
        }

        stage('deploy') {
                steps {
                    script {
                        def selectedEnv = input(
                            message: 'Select the environment to deploy',
                            ok: 'Done',
                            parameters: [
                                choice(name: 'ENV', choices: ['dev', 'staging', 'prod'], description: '')
                            ]
                        )

                        echo 'Deploying the app...'
                        echo 'Using configured server credentials'
                        echo "Environment is ${selectedEnv}"

                        withCredentials([
                            usernamePassword(
                                credentialsId: 'GitLab-nana-java-maven-app',
                                usernameVariable: 'USER',
                                passwordVariable: 'PWD'
                            )
                        ]) {
                            sh 'echo "Deploy step ran successfully"'
                        }
                    }
                }
            }
    }
}